// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0NNwuZVMuvB_vPGnLjLDV1nNVxAQhaD8',
    appId: '1:310351669320:web:12344ec815b192891e107d',
    messagingSenderId: '310351669320',
    projectId: 'faceoff-a34ba',
    authDomain: 'faceoff-a34ba.firebaseapp.com',
    databaseURL: 'https://faceoff-a34ba-default-rtdb.firebaseio.com',
    storageBucket: 'faceoff-a34ba.appspot.com',
    measurementId: 'G-KLEW4WRNDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtBfefnXFkC_2HcagnRi61n5wnvzvn8rc',
    appId: '1:310351669320:android:361191ffe73b70481e107d',
    messagingSenderId: '310351669320',
    projectId: 'faceoff-a34ba',
    databaseURL: 'https://faceoff-a34ba-default-rtdb.firebaseio.com',
    storageBucket: 'faceoff-a34ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_Fnkf15TEQ8S9YoLwncZCKE1CrSzjq0',
    appId: '1:310351669320:ios:b6c3db2a14df0ebd1e107d',
    messagingSenderId: '310351669320',
    projectId: 'faceoff-a34ba',
    databaseURL: 'https://faceoff-a34ba-default-rtdb.firebaseio.com',
    storageBucket: 'faceoff-a34ba.appspot.com',
    iosClientId: '310351669320-65gv88b6kcrbkdqt4himrn7js0k00efu.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceOff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9_Fnkf15TEQ8S9YoLwncZCKE1CrSzjq0',
    appId: '1:310351669320:ios:b6c3db2a14df0ebd1e107d',
    messagingSenderId: '310351669320',
    projectId: 'faceoff-a34ba',
    databaseURL: 'https://faceoff-a34ba-default-rtdb.firebaseio.com',
    storageBucket: 'faceoff-a34ba.appspot.com',
    iosClientId: '310351669320-65gv88b6kcrbkdqt4himrn7js0k00efu.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceOff',
  );
}
